const profileClient=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_KEY);
const form=document.querySelector("#profileForm"),msg=document.querySelector("#profileMsg"),avatar=document.querySelector("#avatar"),fileInput=document.querySelector("#avatarFile");
let currentUser=null;
const fallback="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'%3E%3Crect width='200' height='200' rx='100' fill='%23151a20'/%3E%3Ctext x='100' y='118' text-anchor='middle' fill='%23c7ff4a' font-size='82' font-family='Arial'>D</text></svg>";
async function loadProfile(){
 const {data:{user},error}=await profileClient.auth.getUser(); if(error||!user){location.href="auth.html";return;} currentUser=user;
 const {data}=await profileClient.from("profiles").select("*").eq("id",user.id).maybeSingle();
 const p=data||{}; document.querySelector("#username").value=p.username||""; document.querySelector("#fullName").value=p.full_name||user.user_metadata?.full_name||""; document.querySelector("#phone").value=p.phone||""; document.querySelector("#email").value=user.email||""; document.querySelector("#profileEmail").textContent=user.email||""; document.querySelector("#profileTitle").textContent=p.username?("@"+p.username):"حسابي"; avatar.src=p.avatar_url||fallback;
}
fileInput.onchange=async()=>{const file=fileInput.files?.[0];if(!file||!currentUser)return;if(file.size>5*1024*1024){msg.textContent="الصورة لازم تكون أقل من 5MB.";return;}msg.textContent="جارٍ رفع الصورة…";const ext=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg";const path=currentUser.id+"/avatar."+ext;const up=await profileClient.storage.from("avatars").upload(path,file,{upsert:true,contentType:file.type});if(up.error){msg.textContent="تعذر رفع الصورة: "+up.error.message;return;}const {data:url}=profileClient.storage.from("avatars").getPublicUrl(path);const saved=await profileClient.from("profiles").update({avatar_url:url.publicUrl}).eq("id",currentUser.id);if(saved.error){msg.textContent="تم رفع الصورة لكن تعذر حفظها: "+saved.error.message;return;}avatar.src=url.publicUrl;msg.textContent="تم تحديث الصورة ✓";};
form.onsubmit=async e=>{e.preventDefault();msg.textContent="جارٍ حفظ التغييرات…";const username=document.querySelector("#username").value.trim().replace(/\s+/g,"_"),full_name=document.querySelector("#fullName").value.trim(),phone=document.querySelector("#phone").value.trim(),email=document.querySelector("#email").value.trim();if(username&&!/^[a-zA-Z0-9_.-]{3,30}$/.test(username)){msg.textContent="اسم المستخدم: 3-30 حرف، إنكليزي/أرقام/._- فقط.";return;}const u=await profileClient.from("profiles").update({username:username||null,full_name,phone}).eq("id",currentUser.id);if(u.error){msg.textContent=u.error.message;return;}if(email!==(currentUser.email||"")){const er=await profileClient.auth.updateUser({email});if(er.error){msg.textContent="تم حفظ البيانات، لكن تعذر تغيير الإيميل: "+er.error.message;await loadProfile();return;}msg.textContent="تم حفظ البيانات. افتح رسالة تأكيد الإيميل الجديد."; }else msg.textContent="تم حفظ بيانات الحساب بنجاح ✓";await loadProfile();};
loadProfile();